---
title: "Lit Review Sweep"
author: "Sabir Meah"
date: "2023-03-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
```

```{r}
articles <- read.csv("articles.csv") %>%
  filter(year %in% c(2021, 2022)) %>%
  mutate(year = as.factor(year))
articles <- articles %>%
  mutate(design = word(str_remove(articles$notes, "RAYYAN-INCLUSION: \\{\"Sabir\"=>\"Included\"\\} \\| RAYYAN-LABELS: "))) %>%
  mutate(design = as.factor(design)) %>%
  mutate(date = case_when(
    year == 2021 ~ "2021",
    year == 2022 & month <= 6 ~ "2022H1",
    year == 2022 & month > 6 ~ "2022H2"
  )) %>%
  mutate(date = as.factor(date))
```

```{r}
table(articles$year, articles$design)
prop.table(table(articles$year, articles$design), margin = 1)
```

```{r}
plot <- ggplot(articles, aes(x = year, fill = design)) +
  geom_bar() +
  labs(x = "Year of Publication",
       y = "Number of Papers",
       fill = "Design") +
  scale_fill_brewer(palette="Set1", labels = c("Case-Control", "Cohort", "Test-Negative")) +
  theme_light()

plot

pdf("./Figures/Publication_Designs_By_Year.pdf", width = 7, height = 5)
plot
dev.off()
```

```{r}
table(articles$date)
table(articles$design)
table(articles$date, articles$design)
prop.table(table(articles$date, articles$design), margin = 1)
```

```{r}
design_prop <- as.data.frame(prop.table(table(articles$date, articles$design), margin = 1)) %>%
  rename(date = Var1, design = Var2, prop = Freq) %>%
  mutate(prop = round(prop, 2)) %>%
  mutate(n = as.data.frame(table(articles$date, articles$design))$Freq)
```

```{r}
design_prop_relevel <- design_prop %>%
  mutate(date = factor(date,
                       levels = c("2021", "2022H1", "2022H2"),
                       labels = c("Jan 2021 - Dec 2021", 
                                         "Jan 2022 - Jun 2022",
                                         "Jul 2022 - Dec 2022")))
```

```{r}
articles_relevel <- articles %>%
  mutate(date = factor(date,
                       levels = c("2021", "2022H1", "2022H2"),
                       labels = c("Jan 2021 - Dec 2021", 
                                         "Jan 2022 - Jun 2022",
                                         "Jul 2022 - Dec 2022")))
```



```{r}
plot <- ggplot(articles, aes(x = date, fill = design)) +
  geom_bar() +
  labs(x = "Period of Publication",
       y = "Number of Papers",
       fill = "Study Design") +
  geom_text(data = design_prop, 
            aes(x = date, y = n, fill = design, group = design, label = scales::percent(prop)),
            position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette = "Set1", labels = c("Case-Control", "Cohort", "Test-Negative")) +
  theme_light()

plot

pdf("./Figures/Publication_Designs_By_HalfYear.pdf", width = 7, height = 5)
plot
dev.off()

png("./Figures/Publication_Designs_By_HalfYear.png", width = 7, height = 5, units = "in", res = 400)
plot
dev.off()
```

```{r}
plot <- ggplot(articles_relevel, aes(x = date, fill = design)) +
  geom_bar() +
  labs(x = "Period of Publication",
       y = "Number of Papers",
       fill = "Study Design") +
  geom_text(data = design_prop_relevel, 
            aes(x = date, y = n, fill = design, group = design, label = scales::percent(prop)),
            position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette = "Set1", labels = c("Case-Control", "Cohort", "Test-Negative")) +
  #scale_fill_manual(values = c("#FF7F00", "#377EB8", "#4DAF4A")) + # ChatGPT
  #scale_fill_manual(values = c("#D55E00", "#0072B2", "#009E73")) + # Colorblind website dark
  scale_fill_manual(values = c("#CC79A7", "#0072B2", "#009E73"), labels = c("Case-Control", "Cohort", "Test-Negative")) + # Colorblind website dark 2
  #scale_fill_manual(values = c("#E69F00", "#56B4E9", "#009E73")) + # Colorblind website light
  #scale_fill_manual(values = c("blue", "red", "orange"), labels = c("Case-Control", "Cohort", "Test-Negative")) + # Rest of forest plot scheme
  theme_light()

plot

pdf("./Figures/Publication_Designs_By_HalfYear_Relevel.pdf", width = 7, height = 5)
plot
dev.off()

png("./Figures/Publication_Designs_By_HalfYear_Relevel.png", width = 7, height = 5, units = "in", res = 400)
plot
dev.off()
```

```{r}
# If you do halves for both years...

articles2 <- read.csv("articles.csv") %>%
  filter(year %in% c(2021, 2022)) %>%
  mutate(year = as.factor(year))
articles2 <- articles2 %>%
  mutate(design = word(str_remove(articles2$notes, "RAYYAN-INCLUSION: \\{\"Sabir\"=>\"Included\"\\} \\| RAYYAN-LABELS: "))) %>%
  mutate(design = as.factor(design)) %>%
  mutate(date = factor(case_when(
    year == 2021 & month <= 6 ~ "2021H1",
    year == 2021 & month > 6 ~ "2021H2",
    year == 2022 & month <= 6 ~ "2022H1",
    year == 2022 & month > 6 ~ "2022H2"
  ), 
  levels = c("2021H1", "2021H2", "2022H1", "2022H2"),
  labels = c("Jan 2021 - Jun 2021", "Jul 2021 - Dec 2021", "Jan 2022 - Jun 2022", "Jul 2022 - Dec 2022")
  )) %>%
  mutate(date = as.factor(date))

design_prop2 <- as.data.frame(prop.table(table(articles2$date, articles2$design), margin = 1)) %>%
  rename(date = Var1, design = Var2, prop = Freq) %>%
  mutate(prop = round(prop, 2)) %>%
  mutate(n = as.data.frame(table(articles2$date, articles2$design))$Freq)

ggplot(articles2, aes(x = date, fill = design)) +
  geom_bar() +
  labs(x = "Half-Year of Publication",
       y = "Number of Papers",
       fill = "Design") +
  geom_text(data = design_prop2, 
            aes(x = date, y = n, fill = design, group = design, label = scales::percent(prop)),
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  #scale_fill_brewer(palette="Set1", labels = c("Case-Control", "Cohort", "Test-Negative")) +
  scale_fill_manual(values = c("#CC79A7", "#0072B2", "#009E73"), labels = c("Case-Control", "Cohort", "Test-Negative")) + # Colorblind website dark 2
  theme_light()

ggsave("./Figures/Publication_Designs_By_HalfYear_BothYears.pdf", width = 8, height = 5)
ggsave("./Figures/Publication_Designs_By_HalfYear_BothYears.png", width = 8, height = 5)
```


